### PR TITLE
Allow to disable tls downstream

### PR DESCRIPTION
**Pull request by hikhvar**

### CODE REVIEW

**Comment by hikhvar** [comment]
The tests are passing on my machine. I can not see the outputs of the drone Job. Any hints?

**Comment by DewaldV** [comment]
Here's the output from drone:
```
+ make test
go test -v -cover github.com/uswitch/yggdrasil github.com/uswitch/yggdrasil/cmd github.com/uswitch/yggdrasil/pkg/envoy github.com/uswitch/yggdrasil/pkg/k8s
# github.com/uswitch/yggdrasil/pkg/envoy
pkg/envoy/configurator.go:134:54: not enough arguments in call to makeVirtualHost
	have (*virtualHost)
	want (*virtualHost, int64)
# github.com/uswitch/yggdrasil/pkg/envoy
pkg/envoy/configurator.go:134: not enough arguments in call to makeVirtualHost
	have (*virtualHost)
	want (*virtualHost, int64)
FAIL	github.com/uswitch/yggdrasil/pkg/envoy [build failed]
=== RUN   TestListReturnsEmptyWithNoObjects
--- PASS: TestListReturnsEmptyWithNoObjects (0.10s)
=== RUN   TestReturnsIngresses
--- PASS: TestReturnsIngresses (0.10s)
=== RUN   TestReturnsFromMultipleIngressControllers
--- PASS: TestReturnsFromMultipleIngressControllers (0.20s)
PASS
coverage: 80.0% of statements
ok  	github.com/uswitch/yggdrasil/pkg/k8s	0.413s	coverage: 80.0% of statements
Makefile:19: recipe for target 'test' failed
make: *** [test] Error 2 
```

**Comment by hikhvar** [comment]
Ok, fixed that issue. Rebased the branch on master. Is it possible to trigger a new build? Drone seems to ignore the force-push.

**Comment by Joseph-Irving** [comment]
all green 👍

**Comment by Joseph-Irving** [comment]
this generally looks good, I would appreciate a test to verify this behaviour works as expected.

**Comment by hikhvar** [comment]
Added the tests.

**Pull request merged**
